
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.biomesoplenty]
		enable_compat_biomesoplenty = true
		#Whether sundamage should be applied to vampires in this biome or not
		disable_sundamage_ominous_woods = true

	[Compatibility.survive]
		enable_compat_survive = true
		#Whether vampires should not need to drink
		disableThirstVampires = true
		#Grant vampires cold resistance, but decrease heat resistance
		enableTemperatureVampires = true
		#Increase natural regeneration for vampires
		enableStaminaBoostVampires = true

	[Compatibility.nyctophobia]
		enable_compat_nyctophobia = true
		#Whether sundamage should be applied to vampires in the haunted biomes or not
		disable_sundamage_haunted = true
		#Whether sundamage should be applied to vampires in the other graveyard biomes or not
		disable_sundamage_other = false

	[Compatibility.ctov]
		enable_compat_ctov = true

	[Compatibility.jade]
		enable_compat_jade = true

	[Compatibility.guardvillagers]
		enable_compat_guardvillagers = true

